import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { Check, ChevronLeft, ChevronRight, Plus, Trash2 } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { PageHeader, Panel, Pipeline } from "@/components/shared/ui";
import { useLanguage } from "@/components/layout/app-shell";
import { analysisService } from "@/services";
import { demoScenarios, scenarioToProduct } from "@/lib/demo/scenarios";
import { MARKET_LABELS } from "@/lib/markets";
import type { Product } from "@/types/domain";

export const Route = createFileRoute("/analysis/new")({ head: () => ({ meta: [{ title: "New Analysis — IP-SAKTI" }, { name: "description", content: "Submit product, ingredients, claims, preparation, and innovation information for assessment." }, { property: "og:title", content: "New Analysis — IP-SAKTI" }, { property: "og:description", content: "Submit product information for evidence-backed assessment." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }] }), component: NewAnalysis });
const blank: Product = { name: "", type: "", description: "", intendedUse: "", targetMarket: "", country: "IN", ingredients: [{ id: crypto.randomUUID(), commonName: "", scientificName: "", quantity: "" }], claims: [{ id: crypto.randomUUID(), type: "Traditional use", text: "" }], preparation: "", innovation: "", intakeStatus: { dosageForm: "not_provided", traditionalReference: "not_provided", existingRegistration: "not_provided", existingIP: "not_provided", applicant: "not_provided" } };

function Field({ label, children, wide = false }: { label: string; children: React.ReactNode; wide?: boolean }) { return <label className={wide ? "sm:col-span-2" : ""}><span className="mb-2 block text-sm font-semibold">{label}</span>{children}</label>; }
function NewAnalysis() {
  const [step, setStep] = useState(0); const [form, setForm] = useState(blank); const [errors, setErrors] = useState<string[]>([]); const [running, setRunning] = useState(false); const [stage, setStage] = useState(0); const [failure, setFailure] = useState(""); const navigate = useNavigate(); const { language } = useLanguage();
  const run = async () => { setRunning(true); setStage(0); setFailure(""); const ticker = window.setInterval(() => setStage((s) => Math.min(6, s + 1)), 1200); try { const result = await analysisService.create({ ...form, language }); window.clearInterval(ticker); navigate({ to: "/analysis/$id", params: { id: result.id }, search: { progress: undefined } }); } catch { window.clearInterval(ticker); setRunning(false); setFailure("The analysis could not be completed. Your product information is still saved on this page — you can retry."); } };
  const steps = ["Product", "Ingredients", "Claims", "Preparation / Innovation", "Review"];
  const update = (key: keyof Product, value: Product[keyof Product]) => setForm((old) => ({ ...old, [key]: value }));
  const next = () => { const required = step === 0 ? [[form.name, "Product name"], [form.type, "Product type"], [form.description, "Description"], [form.intendedUse, "Intended use"], [form.targetMarket, "Target market"]] : []; const missing = required.filter(([value]) => !String(value).trim()).map(([, name]) => `${name} is required.`); setErrors(missing); if (!missing.length) setStep((s) => Math.min(4, s + 1)); };
  if (running) return <><PageHeader eyebrow="Analysis in progress" title="Building the evidence assessment" description="Classification, retrieval, validation and routing run in sequence. Completed stages appear as they finish." /><Panel className="mx-auto max-w-3xl p-6 sm:p-8"><Pipeline active={stage} /><p className="mt-6 border-t border-border pt-5 text-sm text-muted-foreground">Your submitted product information is saved with this case.</p></Panel></>;
  return <><PageHeader eyebrow="New assessment" title="Describe the product" description="Provide the evidence context in five focused steps. You can review everything before analysis." />
    <div className="mb-6 overflow-x-auto"><ol className="flex min-w-[650px] items-center">{steps.map((name, i) => <li key={name} className="flex flex-1 items-center"><button onClick={() => i < step && setStep(i)} className="flex min-h-11 items-center gap-2 text-left"><span className={`grid size-8 place-items-center rounded-full border text-sm font-bold ${i < step ? "border-success bg-success text-primary-foreground" : i === step ? "border-primary bg-primary text-primary-foreground" : "border-border bg-card text-muted-foreground"}`}>{i < step ? <Check className="size-4" /> : i + 1}</span><span className={`text-sm font-semibold ${i === step ? "text-foreground" : "text-muted-foreground"}`}>{name}</span></button>{i < steps.length - 1 && <span className="mx-3 h-px flex-1 bg-border" />}</li>)}</ol></div>
    <Panel className="p-5 sm:p-8"><div className="mb-6"><p className="section-label">Step {step + 1} of 5</p><h2 className="mt-1 text-2xl font-semibold">{steps[step]}</h2></div>
      {failure && <div role="alert" className="mb-6 rounded-lg border border-destructive/30 bg-destructive/10 p-4 text-sm text-destructive">{failure}</div>}
      {errors.length > 0 && <div role="alert" className="mb-6 rounded-lg border border-destructive/30 bg-destructive/10 p-4 text-sm text-destructive"><strong>Check the required fields:</strong><ul className="mt-1 list-disc pl-5">{errors.map((e) => <li key={e}>{e}</li>)}</ul></div>}
      {step === 0 && <div className="mb-6 rounded-xl border border-border bg-muted/40 p-4"><label htmlFor="scenario" className="mb-2 block text-sm font-semibold">Load a demo scenario</label><div className="flex flex-wrap items-center gap-3"><select id="scenario" defaultValue="" onChange={(e) => { const found = demoScenarios.find((s) => s.id === e.target.value); if (found) { setForm(scenarioToProduct(found)); setErrors([]); } }} className="h-11 min-w-64 rounded-lg border border-input bg-card px-3 text-sm"><option value="">Start from a blank form</option>{demoScenarios.map((s) => <option key={s.id} value={s.id}>{s.label}</option>)}</select><p className="text-sm text-muted-foreground">Prefills every step with a prepared example. You can edit any field afterwards.</p></div></div>}
      {step === 0 && <div className="grid gap-5 sm:grid-cols-2"><Field label="Product name"><Input value={form.name} onChange={(e) => update("name", e.target.value)} placeholder="e.g. Ashwagandha Herbal Beverage" /></Field><Field label="Product type"><Input value={form.type} onChange={(e) => update("type", e.target.value)} placeholder="Beverage, formulation, cosmetic..." /></Field><Field label="Product description" wide><Textarea value={form.description} onChange={(e) => update("description", e.target.value)} /></Field><Field label="Intended use"><Input value={form.intendedUse} onChange={(e) => update("intendedUse", e.target.value)} /></Field><Field label="Target consumer"><Input value={form.targetMarket} onChange={(e) => update("targetMarket", e.target.value)} /></Field><Field label="Country / market"><select value={form.country} onChange={(e) => update("country", e.target.value)} className="h-11 w-full rounded-lg border border-input bg-card px-3 text-sm">{Object.entries(MARKET_LABELS).map(([code, label]) => <option key={code} value={code}>{label}</option>)}</select></Field><Field label="Existing registration / licence"><Input value={form.existingRegistration ?? ""} onChange={(e) => update("existingRegistration", e.target.value)} placeholder="Not provided / licence number" /></Field><Field label="Existing IP"><Input value={form.existingIP ?? ""} onChange={(e) => update("existingIP", e.target.value)} placeholder="Not provided / application or registration" /></Field></div>}
      {step === 1 && <div className="space-y-4">{form.ingredients.map((ing, i) => <div key={ing.id} className="grid gap-3 rounded-xl border border-border p-4 sm:grid-cols-2 lg:grid-cols-4"><Field label="Ingredient / material"><Input value={ing.commonName} onChange={(e) => update("ingredients", form.ingredients.map((x, n) => n === i ? { ...x, commonName: e.target.value } : x))} placeholder="Ashwagandha root extract" /></Field><Field label="Scientific name"><Input value={ing.scientificName} onChange={(e) => update("ingredients", form.ingredients.map((x, n) => n === i ? { ...x, scientificName: e.target.value } : x))} placeholder="Withania somnifera" /></Field><Field label="Quantity / unit"><Input value={ing.quantity} onChange={(e) => update("ingredients", form.ingredients.map((x, n) => n === i ? { ...x, quantity: e.target.value } : x))} /></Field><Field label="Plant part"><Input value={ing.plantPart ?? ""} onChange={(e) => update("ingredients", form.ingredients.map((x, n) => n === i ? { ...x, plantPart: e.target.value } : x))} placeholder="Root, leaf, seed" /></Field><Field label="Source status"><select value={ing.sourceStatus ?? "unknown"} onChange={(e) => update("ingredients", form.ingredients.map((x, n) => n === i ? { ...x, sourceStatus: e.target.value as typeof x.sourceStatus } : x))} className="h-11 w-full rounded-lg border border-input bg-card px-3 text-sm"><option value="unknown">Unknown</option><option value="cultivated">Cultivated</option><option value="wild">Wild-collected</option></select></Field><Field label="Geographic source"><Input value={ing.geographicSource ?? ""} onChange={(e) => update("ingredients", form.ingredients.map((x, n) => n === i ? { ...x, geographicSource: e.target.value } : x))} placeholder="Region / country" /></Field><Field label="Supplier"><Input value={ing.supplier ?? ""} onChange={(e) => update("ingredients", form.ingredients.map((x, n) => n === i ? { ...x, supplier: e.target.value } : x))} /></Field><Button variant="ghost" size="icon" className="self-end" aria-label="Remove ingredient" title="Remove ingredient" onClick={() => update("ingredients", form.ingredients.filter((_, n) => n !== i))}><Trash2 /></Button></div>)}<Button variant="outline" onClick={() => update("ingredients", [...form.ingredients, { id: crypto.randomUUID(), commonName: "", scientificName: "", quantity: "" }])}><Plus />Add ingredient</Button></div>}
      {step === 2 && <div className="space-y-4">{form.claims.map((claim, i) => <div key={claim.id} className="grid gap-3 rounded-xl border border-border p-4 sm:grid-cols-[180px_1fr_44px]"><Field label="Claim type"><select value={claim.type} onChange={(e) => update("claims", form.claims.map((x, n) => n === i ? { ...x, type: e.target.value as typeof claim.type } : x))} className="h-11 w-full rounded-lg border border-input bg-card px-3 text-sm"><option>Traditional use</option><option>Functional</option><option>Health</option></select></Field><Field label="Claim wording"><Input value={claim.text} onChange={(e) => update("claims", form.claims.map((x, n) => n === i ? { ...x, text: e.target.value } : x))} /></Field><Button variant="ghost" size="icon" className="self-end" aria-label="Remove claim" title="Remove claim" onClick={() => update("claims", form.claims.filter((_, n) => n !== i))}><Trash2 /></Button></div>)}<Button variant="outline" onClick={() => update("claims", [...form.claims, { id: crypto.randomUUID(), type: "Functional", text: "" }])}><Plus />Add claim</Button></div>}
      {step === 3 && <div className="grid gap-5 sm:grid-cols-2"><Field label="Preparation, extraction, processing and manufacturing method" wide><Textarea value={form.preparation} onChange={(e) => update("preparation", e.target.value)} placeholder="Describe the preparation method, extraction, processing, and manufacturing steps." /></Field><Field label="Formulation, ingredient or technological innovation" wide><Textarea value={form.innovation} onChange={(e) => update("innovation", e.target.value)} placeholder="Describe modifications, novel ingredients, process changes, or technical innovation." /></Field><Field label="Dosage form"><Input value={form.dosageForm ?? ""} onChange={(e) => update("dosageForm", e.target.value)} placeholder="Powder, capsule, beverage..." /></Field><Field label="Traditional text reference"><Input value={form.traditionalReference ?? ""} onChange={(e) => update("traditionalReference", e.target.value)} placeholder="Text, monograph or not provided" /></Field><Field label="Applicant / organisation"><Input value={form.applicant?.organisation ?? ""} onChange={(e) => update("applicant", { ...(form.applicant ?? {}), organisation: e.target.value })} /></Field><Field label="Applicant name"><Input value={form.applicant?.name ?? ""} onChange={(e) => update("applicant", { ...(form.applicant ?? {}), name: e.target.value })} /></Field><Field label="Applicant email"><Input type="email" value={form.applicant?.email ?? ""} onChange={(e) => update("applicant", { ...(form.applicant ?? {}), email: e.target.value })} /></Field><Field label="Applicant address"><Input value={form.applicant?.address ?? ""} onChange={(e) => update("applicant", { ...(form.applicant ?? {}), address: e.target.value })} /></Field></div>}
      {step === 4 && <div className="grid gap-4 lg:grid-cols-2">{[{ title: "Product", body: `${form.name || "Not provided"} · ${form.type || "Not provided"}\n${form.description || "No description"}` }, { title: "Target market", body: `${form.country}\n${form.targetMarket || "Not provided"}` }, { title: "Ingredients", body: form.ingredients.map((i) => `${i.commonName || "Unnamed"}${i.scientificName ? ` (${i.scientificName})` : ""} — ${i.quantity || "Quantity not provided"}`).join("\n") || "None added" }, { title: "Claims", body: form.claims.map((c) => `${c.type}: ${c.text || "No wording"}`).join("\n") || "None added" }, { title: "Preparation", body: form.preparation || "Not provided" }, { title: "Innovation", body: form.innovation || "Not provided" }].map((item, i) => <div key={item.title} className="rounded-xl border border-border p-5"><div className="flex justify-between"><h3 className="font-semibold">{item.title}</h3><button onClick={() => setStep(i > 3 ? 3 : i === 1 ? 0 : i)} className="min-h-11 text-sm font-semibold text-primary">Edit</button></div><p className="whitespace-pre-line text-sm text-muted-foreground">{item.body}</p></div>)}</div>}
      <div className="mt-8 flex justify-between border-t border-border pt-6"><Button variant="outline" disabled={step === 0} onClick={() => setStep((s) => s - 1)}><ChevronLeft />Back</Button>{step < 4 ? <Button onClick={next}>Continue<ChevronRight /></Button> : <Button onClick={run}>Run Analysis<ChevronRight /></Button>}</div>
    </Panel></>;
}
