import { AlertTriangle, ArrowRight, Check, Circle, Clock3, ExternalLink, LoaderCircle, Search } from "lucide-react";
import type { ReactNode } from "react";
import { Link } from "@tanstack/react-router";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import type { Status } from "@/types/domain";

export function PageHeader({ eyebrow, title, description, actions }: { eyebrow?: string; title: string; description: string; actions?: ReactNode }) { return <header className="mb-8 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div className="max-w-3xl">{eyebrow && <p className="section-label mb-2">{eyebrow}</p>}<h1 className="text-3xl font-bold tracking-normal sm:text-4xl">{title}</h1><p className="mt-2 text-base text-muted-foreground">{description}</p></div>{actions && <div className="flex flex-wrap gap-3">{actions}</div>}</header>; }
export function Panel({ children, className = "" }: { children: ReactNode; className?: string }) { return <section className={cn("research-surface", className)}>{children}</section>; }
export function StatusBadge({ status }: { status: Status }) { const style = status === "complete" ? "bg-success-soft text-success" : status === "processing" ? "bg-info-soft text-info" : status === "failed" ? "bg-destructive/10 text-destructive" : status === "review" ? "bg-warning-soft text-warning" : "bg-muted text-muted-foreground"; const label = status === "review" ? "Needs review" : `${status.charAt(0).toUpperCase()}${status.slice(1)}`; return <span className={cn("inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-xs font-semibold", style)}>{status === "complete" && <Check className="size-3" />}{status === "processing" && <LoaderCircle className="size-3 animate-spin" />}{label}</span>; }
export function Confidence({ value, label }: { value: number; label?: string }) { const tone = value >= 80 ? "bg-success" : value >= 65 ? "bg-warning" : "bg-destructive"; return <div className="min-w-32"><div className="mb-1.5 flex items-baseline justify-between gap-3"><strong className="text-lg">{value}%</strong><span className="text-xs text-muted-foreground">{label ?? (value >= 80 ? "High" : value >= 65 ? "Moderate" : "Low")}</span></div><div className="h-1.5 overflow-hidden rounded-full bg-muted"><div className={cn("h-full rounded-full", tone)} style={{ width: `${value}%` }} /></div></div>; }
export function EmptyState({ title, description, action }: { title: string; description: string; action?: ReactNode }) { return <div className="research-surface grid min-h-64 place-items-center p-8 text-center"><div><Search className="mx-auto mb-4 size-8 text-muted-foreground" /><h2 className="font-semibold">{title}</h2><p className="mt-2 max-w-sm text-sm text-muted-foreground">{description}</p>{action && <div className="mt-5">{action}</div>}</div></div>; }
export function ReviewNotice({ reason, action }: { reason: string; action: string }) { return <Panel className="border-warning/30 bg-warning-soft p-6"><div className="flex gap-4"><span className="grid size-10 shrink-0 place-items-center rounded-lg bg-warning/10 text-warning"><AlertTriangle className="size-5" /></span><div><h2 className="text-lg font-semibold">Expert review recommended</h2><p className="mt-1 text-sm text-muted-foreground">The available evidence does not provide sufficient confidence for an automated conclusion.</p><dl className="mt-4 grid gap-3 text-sm"><div><dt className="font-semibold">Reason</dt><dd className="text-muted-foreground">{reason}</dd></div><div><dt className="font-semibold">Recommended action</dt><dd className="text-muted-foreground">{action}</dd></div></dl></div></div></Panel>; }
export function Pipeline({ active = 3 }: { active?: number }) { const steps = ["Product information received", "Product classification", "Evidence retrieval", "Evidence validation", "IP pathway assessment", "Regulatory routing", "Checklist generation"]; return <ol className="space-y-1">{steps.map((step, i) => { const done = i < active; const current = i === active; return <li key={step} className={cn("flex items-center gap-4 rounded-lg p-4", current && "bg-info-soft")}><span className={cn("grid size-8 shrink-0 place-items-center rounded-full border", done ? "border-success bg-success text-primary-foreground" : current ? "border-info text-info" : "border-border text-muted-foreground")}>{done ? <Check className="size-4" /> : current ? <LoaderCircle className="size-4 animate-spin" /> : <Circle className="size-3" />}</span><div><p className="font-medium">{step}</p><p className="text-xs text-muted-foreground">{done ? "Completed" : current ? "Processing" : "Pending"}</p></div></li>; })}</ol>; }
export function ActionLink({ to, children }: { to: "/analysis/new" | "/cases" | "/evidence"; children: ReactNode }) { return <Button asChild><Link to={to}>{children}<ArrowRight /></Link></Button>; }
export function OfficialLink({ url }: { url: string | undefined }) { return url ? <Button variant="outline" asChild><a href={url} target="_blank" rel="noreferrer">Open Official Source<ExternalLink /></a></Button> : <span className="text-sm text-muted-foreground">Official link unavailable</span>; }
export function Meta({ icon: Icon = Clock3, children }: { icon?: typeof Clock3; children: ReactNode }) { return <span className="inline-flex items-center gap-1.5 text-xs text-muted-foreground"><Icon className="size-3.5" />{children}</span>; }